export const categoriesData = {
  MEN: {
    Tops: [
      "T-Shirts",
      "Dress Shirts",
      "Polo Shirts",
      "Henley Shirts",
      "Casual Button-Up Shirts",
      "Sweaters",
      "Hoodies",
    ],
    Bottoms: [
      "Jeans",
      "Trousers",
      "Chinos",
      "Shorts",
      "Cargo Pants",
      "Sweatpants",
      "Joggers",
    ],
    "Suits and Formal Wear": [
      "Business Suits",
      "Tuxedos",
      "Blazers",
      "Dress Pants",
      "Waistcoats",
      "Dress Shirts",
    ],
    Outerwear: [
      "Jackets",
      "Coats",
      "Overcoats",
      "Parkas",
      "Pea Coats",
      "Bomber Jackets",
      "Leather Jackets",
    ],
    Activewear: [
      "Athletic Shorts",
      "Athletic T-Shirts",
      "Track Pants",
      "Running Shorts",
      "Performance Hoodies",
      "Sports Jerseys",
      "Compression Gear",
    ],
    Underwear: [
      "Boxer Briefs",
      "Boxers",
      "Briefs",
      "Trunks",
      "Thermal Underwear",
      "Undershirts",
      "Long Johns",
    ],
    Sleepwear: [
      "Pajama Sets",
      "Sleep Shorts",
      "Sleep Pants",
      "Robes",
      "Lounge Pants",
      "Onesies",
    ],
    Swimwear: ["Swim Trunks", "Board Shorts", "Swim Briefs", "Rash Guards"],
    Footwear: [
      "Sneakers",
      "Dress Shoes",
      "Casual Shoes",
      "Boots",
      "Loafers",
      "Sandals",
      "Athletic Shoes",
    ],
    Workwear: [
      "Dress Shirts",
      "Dress Pants",
      "Business Suits",
      "Ties",
      "Work Boots",
      "Safety Gear",
    ],
    "Casual Wear": [
      "Graphic T-Shirts",
      "Cargo Shorts",
      "Denim Jackets",
      "Flannel Shirts",
      "Casual Sneakers",
      "Baseball Caps",
    ],
    "Outdoor and Adventure Clothing": [
      "Hiking Pants",
      "Outdoor Jackets",
      "Performance Fleece",
      "Waterproof Boots",
      "Camping Gear",
    ],
    "Ethnic and Cultural Attire": [
      "Kimono",
      "Dashiki",
      "Kilt",
      "Sherwani",
      "Thobe",
      "Djellaba",
      "Lederhosen",
    ],
  },
  WOMEN: {
    Tops: [
      "T-Shirts",
      "Blouses",
      "Tank Tops",
      "Sweaters",
      "Hoodies",
      "Tunics",
      "Crop Tops",
    ],
    Bottoms: [
      "Jeans",
      "Leggings",
      "Trousers",
      "Skirts",
      "Shorts",
      "Palazzo Pants",
      "Culottes",
    ],
    Dresses: [
      "Casual Dresses",
      "Formal Dresses",
      "Maxi Dresses",
      "Midi Dresses",
      "Mini Dresses",
      "Wrap Dresses",
      "Bodycon Dresses",
    ],
    Outerwear: [
      "Jackets",
      "Coats",
      "Blazers",
      "Parkas",
      "Cardigans",
      "Ponchos",
      "Vests",
    ],
    Activewear: [
      "Yoga Pants",
      "Sports Bras",
      "Athletic Shorts",
      "Workout Leggings",
      "Running Tops",
      "Hooded Sweatshirts",
      "Athletic Jackets",
    ],
    "Lingerie and Sleepwear": [
      "Bras",
      "Panties",
      "Lingerie Sets",
      "Nightgowns",
      "Pajama Sets",
      "Robes",
      "Camisoles",
    ],
    Swimwear: [
      "Bikinis",
      "One-Piece Swimsuits",
      "Tankinis",
      "Cover-Ups",
      "Rash Guards",
      "Swim Shorts",
    ],
    Footwear: [
      "Sneakers",
      "Sandals",
      "Boots",
      "Flats",
      "Heels",
      "Wedges",
      "Espadrilles",
    ],
    "Maternity Wear": [
      "Maternity Dresses",
      "Maternity Jeans",
      "Maternity Tops",
      "Maternity Activewear",
      "Maternity Outerwear",
      "Nursing Bras",
    ],
    "Plus-Size Clothing": [
      "Plus-Size Tops",
      "Plus-Size Bottoms",
      "Plus-Size Dresses",
      "Plus-Size Lingerie",
      "Plus-Size Activewear",
      "Plus-Size Outerwear",
    ],
    "Special Occasion Wear": [
      "Evening Gowns",
      "Cocktail Dresses",
      "Ballgowns",
      "Wedding Dresses",
      "Bridesmaid Dresses",
      "Prom Dresses",
    ],
    Workwear: [
      "Business Suits",
      "Blouses",
      "Pencil Skirts",
      "Dress Pants",
      "Blazer Jackets",
      "Work Dresses",
    ],
    "Ethnic and Cultural Attire": [
      "Sari",
      "Kimono",
      "Abaya",
      "Cheongsam",
      "Dashiki",
      "Hanbok",
      "Dirndl",
    ],
  },
  KIDS: {
    "Baby Clothing": [
      "Onesies",
      "Rompers",
      "Baby Sleepers",
      "Baby Bodysuits",
      "Baby T-Shirts",
      "Diaper Covers",
    ],
    Tops: ["T-Shirts", "Blouses", "Polos", "Sweaters", "Hoodies", "Tank Tops"],
    Bottoms: ["Pants", "Leggings", "Jeans", "Shorts", "Skirts", "Overalls"],
    Dresses: [
      "Casual Dresses",
      "Formal Dresses",
      "Sundresses",
      "Party Dresses",
      "Maxi Dresses",
    ],
    Outerwear: [
      "Jackets",
      "Coats",
      "Snowsuits",
      "Raincoats",
      "Vests",
      "Fleece Jackets",
    ],
    Activewear: [
      "Athletic Shorts",
      "Sports Jerseys",
      "Tracksuits",
      "Sports Bras",
      "Gym Leggings",
      "Athletic T-Shirts",
    ],
    Sleepwear: [
      "Pajama Sets",
      "Sleep Gowns",
      "Sleep Shirts",
      "Sleep Pants",
      "Robes",
      "Onesies",
    ],
    Swimwear: [
      "Swim Trunks",
      "Swimsuits",
      "Rash Guards",
      "Swim Diapers",
      "Cover-Ups",
    ],
    Underwear: [
      "Underwear Sets",
      "Briefs",
      "Boxer Briefs",
      "Training Pants",
      "Camisoles",
      "Undershirts",
    ],
    Footwear: [
      "Baby Booties",
      "Infant Shoes",
      "Toddler Shoes",
      "Kids' Sneakers",
      "Sandals",
      "Rain Boots",
      "Snow Boots",
    ],
    "School Uniforms": [
      "Polo Shirts",
      "Dress Shirts",
      "Dress Pants",
      "Skirts",
      "Blazers",
      "Ties",
    ],
    "Special Occasion Wear": [
      "Flower Girl Dresses",
      "Boys' Suits",
      "Christening Gowns",
      "Communion Dresses",
      "Holiday Outfits",
    ],
    "Toddler and Infant Clothing": [
      "Toddler Suits",
      "Toddler Dresses",
      "Toddler T-Shirts",
      "Baby Sets",
      "Baby Pajamas",
    ],
    "Ethnic and Cultural Attire": [
      "Traditional Cultural Outfits",
      "Ethnic Dresses",
      "Cultural Accessories",
    ],
  },
};
